import pytest
from src.config import settings
from src.database import get_database


async def test_mailbox_ttl_index_configured():
    """Verify the mailboxes collection has the proper TTL index and expiry set."""
    db = get_database()
    indexes = await db["mailboxes"].index_information()

    # Index name generated by Motor/Mongo is 'created_at_1'
    assert "created_at_1" in indexes, "created_at index was not found on mailboxes collection"

    ttl_index = indexes["created_at_1"]
    assert ttl_index["key"] == [("created_at", 1)]
    assert ttl_index["expireAfterSeconds"] == settings.MAILBOX_EXPIRY_SECONDS